export const themeData = [
  {
    title: "浪漫愛情",
    src: "theme/10749.png",
    target: "10749",
    genreId: 10749,
    type: "movie",
  },
  {
    title: "熱門韓劇",
    src: "theme/18.png",
    target: "18",
    genreId: 18,
    original: "ko",
    type: "tv",
  },
  {
    title: "喜劇之王",
    src: "theme/35.png",
    target: "35",
    genreId: 35,
    type: "movie",
  },
  {
    title: "驚悚恐怖",
    src: "theme/27.png",
    target: "27",
    genreId: 27,
    type: "movie",
  },
  {
    title: "燒腦懸疑",
    src: "theme/9468.png",
    target: "9648",
    genreId: 9648,
    type: "movie",
  },
  {
    title: "動作冒險",
    src: "theme/28.png",
    target: "28",
    genreId: 28,
    type: "movie",
  },
  {
    title: "動漫動畫",
    src: "theme/16.png",
    target: "16",
    genreId: 16,
    type: "tv",
  },
  {
    title: "喪失、病毒",
    src: "theme/zombie.png",
    target: "zombie",
    keyword: "zombie",
    type: "movie",
  },
  {
    title: "Netflix 經典",
    src: "theme/netflix.png",
    target: "netflix",
    keyword: "netflix",
    type: "tv",
  },
];
